# Generated by Django 4.1.7 on 2023-03-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=500)),
                ('tech', models.CharField(max_length=100)),
                ('estimatedHrs', models.IntegerField()),
                ('startdate', models.DateTimeField()),
                ('completitiondate', models.DateTimeField()),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('estimatedHrs', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('priority', models.CharField(choices=[('high', 'high'), ('low', 'low'), ('medium', 'medium')], max_length=20)),
                ('desc', models.CharField(max_length=500)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectmodule')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.status')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
