# Generated by Django 4.1.7 on 2023-03-23 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodule',
            old_name='pid',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectteam',
            old_name='pid',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='mid',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='pid',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='sid',
            new_name='status',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
