# Generated by Django 4.1.7 on 2023-04-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_usertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('inProgress', 'inProgress'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
