# Generated by Django 4.1.7 on 2023-03-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_developr',
            new_name='is_developer',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager1',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
